---
# tasks file for audit
- name: Configure auditd admin_space_left Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "admin_space_left_action = single"
    regexp: "^admin_space_left_action*"
  notify: reload auditd  

- name: Deploy audit rules
  template:
    src: "{{ item }}"
    dest: "/etc/audit/rules.d/{{ item }}"
    owner: root
    group: root
    mode: 0600
  loop:
    - access.rules
    - actions.rules
    - audit_rules_networkconfig_modification.rules
    - audit_rules_usergroup_modification.rules
    - delete.rules
    - audit_time_rules.rules
    - export.rules
    - immutable.rules
    - MAC-policy.rules
    - logins.rules
    - modules.rules
    - perm_mod.rules
    - session.rules
    - privileged.rules
    - time-change.rules
  notify: reload auditd