---
# tasks file for access-control
- name: Set Password Warning Age
  lineinfile:
      create: yes
      dest: /etc/login.defs
      regexp: ^#?PASS_WARN_AGE
      line: "PASS_WARN_AGE {{ var_accounts_warning_age_login_defs }}"

- name: Set Password Minimum Age
  lineinfile:
      create: yes
      dest: /etc/login.defs
      regexp: ^#?PASS_MIN_DAYS
      line: "PASS_MIN_DAYS {{ var_accounts_minimum_age_login_defs }}"

- name: Set Password Maximum Age
  lineinfile:
    create: yes
    dest: /etc/login.defs
    regexp: ^#?PASS_MAX_DAYS
    line: "PASS_MAX_DAYS {{ var_accounts_maximum_age_login_defs }}"


- name: Ensure PAM variable minlen is set accordingly
  lineinfile:
    create: yes
    dest: "/etc/security/pwquality.conf"
    regexp: '^#?\s*minlen'
    line: "minlen = {{ var_password_pam_minlen }}"

- name: Ensure PAM variable dcredit is set accordingly
  lineinfile:
    create: yes
    dest: "/etc/security/pwquality.conf"
    regexp: '^#?\s*dcredit'
    line: "dcredit = {{ var_password_pam_dcredit }}"

- name: Ensure PAM variable lcredit is set accordingly
  lineinfile:
    create: yes
    dest: "/etc/security/pwquality.conf"
    regexp: '^#?\s*lcredit'
    line: "lcredit = {{ var_password_pam_lcredit }}"

- name: Ensure PAM variable ucredit is set accordingly
  lineinfile:
    create: yes
    dest: "/etc/security/pwquality.conf"
    regexp: '^#?\s*ucredit'
    line: "ucredit = {{ var_password_pam_ucredit }}"

- name: Modify the System Login Banner
  script: etc-issue.sh

- name: Ensure the Default Bash Umask is Set Correctly
  script: bash-umask.sh

- name: Ensure the Default Umask is Set Correctly in /etc/profile
  script: profile-umask.sh

